83 project set up scripts arent os agnostic
CodeForPhilly/pa-wildflower-selector pull request #96
Opened 2024-02-11 14:49 UTC by ZacharyLeahan

I added "npm run restore-test-data-win" as "npm run restore-test-data" did not run in Windows.
"npm run restore-test-data-win" is os agnostic as it relies on a js script. This is tested on my windows machine.

This pull request is for the js script, package.json reference, and readme update.

Evidence of this running locally:
![image](https://github.com/CodeForPhilly/pa-wildflower-selector/assets/54847203/95686f58-9675-4beb-af72-07b050d613eb)
![image](https://github.com/CodeForPhilly/pa-wildflower-selector/assets/54847203/21fe1db4-227b-4710-850e-bf754a1dd7af)

2024-02-11 19:36 UTC, boutell requested changes
The request for changes is mostly about the minor confusion in the README, my comment about your promise chain based code is more about taking it in a direction you'll find a lot easier to maintain in the long run but it's up to you.

2024-02-11 19:36 UTC, boutell commented on README.md
> +mongosh mongodb://localhost:27017/pa-wildflower-selector
This doesn't run an instance of mongodb, you already did that by setting it up to "install mongod as a service." This opens the mongo shell, which is nice but not required for anything we do below I think. You could just say "for Windows, this happened automatically when you installed mongod as a service."

2024-02-11 19:36 UTC, boutell commented on scripts/restore-test-data.js
> +const https = require('https');
This is impressive, but you're working way harder than you have to here by using promise chains (calling `then()` and `catch()` functions in chains etc). Using promise constructors and chains is not necessary anymore. You should switch this up to use `async/await` so your code can read as a simple linear series of steps. It's a lot easier to maintain.

There's a pretty good tutorial here:

https://javascript.info/async-await

2024-11-01 11:10 UTC, ZacharyLeahan commented
This isn't needed since git shell works on windows.

2024-11-01 11:10 UTC, closed without merging